# Generated by Django 3.1.1 on 2020-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        {% for n in cookiecutter.models.name %}
    migrations.CreateModel(
        name='{{n}}',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=20)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
    ),
        {% endfor %}

    ]
